// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVvlnFsF66Nwfl-26Mf-M3Kff4kbo-kA',
    appId: '1:492248015244:web:f883ddd85161dbb192b6a9',
    messagingSenderId: '492248015244',
    projectId: 'mad3-finals-tuba',
    authDomain: 'mad3-finals-tuba.firebaseapp.com',
    storageBucket: 'mad3-finals-tuba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQDnSmAwBgkN42gWGj_AGd5r3O2hDzvfM',
    appId: '1:492248015244:android:651505dd4723548192b6a9',
    messagingSenderId: '492248015244',
    projectId: 'mad3-finals-tuba',
    storageBucket: 'mad3-finals-tuba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF3PKtaYAZB6qeNAOyzbNK1R_g8LdtqjM',
    appId: '1:492248015244:ios:160b7fca032c74ed92b6a9',
    messagingSenderId: '492248015244',
    projectId: 'mad3-finals-tuba',
    storageBucket: 'mad3-finals-tuba.appspot.com',
    iosBundleId: 'com.example.mad3FinalsTuba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF3PKtaYAZB6qeNAOyzbNK1R_g8LdtqjM',
    appId: '1:492248015244:ios:160b7fca032c74ed92b6a9',
    messagingSenderId: '492248015244',
    projectId: 'mad3-finals-tuba',
    storageBucket: 'mad3-finals-tuba.appspot.com',
    iosBundleId: 'com.example.mad3FinalsTuba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVvlnFsF66Nwfl-26Mf-M3Kff4kbo-kA',
    appId: '1:492248015244:web:0721d63347b5258992b6a9',
    messagingSenderId: '492248015244',
    projectId: 'mad3-finals-tuba',
    authDomain: 'mad3-finals-tuba.firebaseapp.com',
    storageBucket: 'mad3-finals-tuba.appspot.com',
  );
}
